name: Generate Snake Graph

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: Platane/snk@v3
        with:
          github_user_name: rabianaveed012-prog
          outputs: |
            dist/github-user-contribution-grid-snake-dark.svg?color_snake=#C084FC&color_dots=#0D1117,#3B0764,#6B21A8,#9333EA,#C084FC

      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
